FROM node:20-alpine
WORKDIR /src/app
COPY package.json yarn.lock /src/app/
RUN yarn install --freeze-lockfile
ARG NEXT_PUBLIC_BASE_HTTP_URL
ARG NEXT_PUBLIC_BASE_WS_URL
ENV NEXT_PUBLIC_BASE_HTTP_URL=$NEXT_PUBLIC_BASE_HTTP_URL
ENV NEXT_PUBLIC_BASE_WS_URL=$NEXT_PUBLIC_BASE_WS_URL
COPY . .
ENV PORT 3000
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]